//------------------------------------------------------------------------------
// <auto-generated>
// This script was generated by XiheFramework
// Generation Time (UTC): 6/14/2025 11:05:59 PM
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConstant{
    public static class ResourceAddresses {
		public const string DefaultLocalGroup_ConsoleUIOverlay = "UIOverlayEntity_ConsoleUIOverlay";
		public const string Board_BoardCellEntity = "BoardCellEntity_BoardCellEntity";
		public const string CsvToJsonData_BuffTableJson = "TextAsset_BuffTableJson";
		public const string CsvToJsonData_CardEffectTableJson = "TextAsset_CardEffectTableJson";
		public const string CsvToJsonData_CardTableJson = "TextAsset_CardTableJson";
		public const string CsvToJsonData_UnitTableJson = "TextAsset_UnitTableJson";
    }
}