//------------------------------------------------------------------------------
// <auto-generated>
// This script was generated by XiheFramework
// Generation Time (UTC): 7/11/2025 10:37:51 PM
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConstant{
    public static class ResourceAddresses {
		public const string DefaultLocalGroup_ConsoleUIOverlay = "UIOverlayEntity_ConsoleUIOverlay";
		public const string Board_BoardCellEntity = "BoardCellEntity_BoardCellEntity";
		public const string Board_BoardEntity = "BoardEntity_BoardEntity";
		public const string CsvToJsonData_BuffTableJson = "TextAsset_BuffTableJson";
		public const string CsvToJsonData_CardEffectTableJson = "TextAsset_CardEffectTableJson";
		public const string CsvToJsonData_CardTableJson = "TextAsset_CardTableJson";
		public const string CsvToJsonData_UnitTableJson = "TextAsset_UnitTableJson";
		public const string Scene_Game = "SceneAsset_Game";
		public const string Scene_Title = "SceneAsset_Title";
    }
}